language: objective-c

before_install:
  - gem install cocoapods -v 0.28.0
  - brew update
  - brew uninstall xctool && brew install xctool

xcode_workspace: Rebelle.xcworkspace
xcode_scheme: Rebelle
xcode_sdk:
  - iphonesimulator6.1
  - iphonesimulator7.0