language: objective-c

before_install:
  - gem install cocoapods -v 0.27.1
  - brew update
  - brew uninstall xctool && brew install xctool

xcode_workspace: Rebelle.xcworkspace
xcode_scheme:    Rebelle
xcode_sdk:       iphonesimulator

matrix:
  include:
    -
      xcode_scheme: Rebelle-OSX
      xcode_sdk:    macosx